### ISSUE TITLE
Encode/Decode vs. Marshal/Unmarshal

### ISSUE THREAD

**Issue by dangerousHobo** [zombiezen/go-capnproto2#43]
Hello,

Why or when would I want to use one over the other?

Thanks.

**Comment by zombiezen** [comment]
These functions are intentionally similar to their counterparts in the `encoding/json` package: use Marshal/Unmarshal when you need to work with byte slices (in-memory), use Encode/Decode when you need to work with a reader/writer (file or other stream).  The added advantage with Unmarshal is since the byte slice is already constructed and available, it will not copy the bytes, so struct accesses will operate on the byte slice in-place.

**Comment by dangerousHobo** [comment]
Awesome, Thanks.
