### ISSUE TITLE
capnproto message grows over time

### ISSUE THREAD

**Issue by dangerousHobo** [zombiezen/go-capnproto2#87]
Hello. I've noticed a capnproto message grows over time and this has caused memory exhustion issues on our system. We keep the message in FRAM and it gets updated every few seconds and after a few weeks we exhust all available FRAM and can't write to the capnproto message anymore.

I've mocked up a small example to show the issue.

My example schema:
```
using Go = import "/go.capnp";

@0xd517470da2b2a883;
$Go.package("foo");
$Go.import("crown/cnptest/foo");

struct Foo {
	bar @0 :Text;
}
```

Example code:
```
package main

import (
	"fmt"
	"os"

	foo "crown/cnptest/foo"
	capnp "zombiezen.com/go/capnproto2"
)

func main() {
	// Create new message
	msg, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))
	if err != nil {
		os.Exit(1)
	}
	obj, err := foo.NewRootFoo(seg)
	if err != nil {
		os.Exit(1)
	}

	obj.SetBar("foobar")
	m, _ := msg.Marshal()
	fmt.Printf("%v\n", len(m))

	obj.SetBar("barfoo")
	m, _ = msg.Marshal()
	fmt.Printf("%v\n", len(m))

	obj.SetBar("abc")
	m, _ = msg.Marshal()
	fmt.Printf("%v\n", len(m))
}
```

Output:
```
32
40
48
```

Am I just doing something wrong? Is there a way to avoid the message growth as fields in the message get updated?

Thanks.

**Comment by zombiezen** [comment]
This question comes up from time to time and is a cross-language concern. @kentonv, perhaps we should create an FAQ entry?  For now, the closest one to describing this problem is https://capnproto.org/faq.html#how-do-i-resize-a-list.

Basically, once an object gets added to a Cap'n Proto message, the space is never reclaimed from the message.  To perform a "compaction", you would mutate the message like you have now, and then copy the root pointer to a new message (`Message.RootPtr` and `Message.SetRootPtr`).  Since the copy operation will only copy what is used, then the new message will not have the old values present.  (#84 is tracking zeroing out the old values in the original message so that the packed serialization will reclaim the space.)

**Comment by zombiezen** [comment]
Closing since this has been open for a week. Feel free to open back up if there's any followup.
